### ISSUE TITLE
Flesh out plugins ideas

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#122]
Plugins aren't coming for a little bit, but this issue is just here to remind us to think about them, and as a dumping ground for any ideas we have in the meantime.
# Plugin Points
- Filter types (already there, sort of)
- Resource factory types (filesystem, tarball, zip (see #406), JAR, network, Git repository)
- Resource type (plain text, Word document, PDF)
- Adding new options (`--dirty` for Git/Hg)
- Search backends (ag, git-grep, code search, mdfind)
- Ignore types (this kind of falls under filter types, but I think it bears mentioning.  See #28)
- Custom search types (`re::engine::RE2` comes to mind, but I was also thinking a special search for Perl using PPI)
- Custom resource searchers (more complex than custom search types; think things like searching an XML file for an XPath expression)

**Comment by petdance** [comment]
We're dumping plugins.
