### ISSUE TITLE
Ignore minified JS files based on content

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#123]
I have a half-fix for this here:

```
http://hoelz.ro/blog/ignoring-minified-javascript-files-with-ack-2
```

We should be able to get around the header issue, though, and have a way to get around having to open every single file.  I was thinking an 'and' filter:

```
--ignore-file=and:(ext:js):(firstlinematch:/.{200}/)
```

**Comment by petdance** [comment]
This is covered by other tickets and feature requests.
