### ISSUE TITLE
Fixing inconsistencies in --man and --help output

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#159]
This list of things may overlap with other documentation-related issues, but to me, it's a pretty comprehensive list of what's incorrect in our current documentation, at least with regards to options:
- `--colour` is not documented in `--man` ( **DONE** )
- `-g` explanation in `--help`/`--man` is no longer accurate ( **DONE** )
- Clarify that `-H` is the default unless you're searching a single explicitly specified file
- `-i`, `-v`, `-Q`, `--smart-case` + `-g` needs fixing in `--man`
- `--man` uses the wording "--match REGEX", but `--help` uses "--match PATTERN"
- `--type-set`/`--type-add` in both `--help` and `--man` both explain old usage (see also Defining your own types in `--man`)
- We should probably document the caveats when using `-w`
  - It might be nice to deliver a warning when using `-w` and a pattern that triggers that behavior.
- `--ignore-ack-defaults`, `--ackrc`, and `--dump` are not found in the options section of `--man` ( **DONE** )
- We sometimes refer to `--line`, and sometimes to `--lines`.  Make sure we only ever refer to `--line` (or is it `--lines`?).
  - The option specification is `--lines`, but ack 1 documentation seems to indicate `--line`.
- We have `--with-filename`, but not `--without-filename` (we use `--no-filename`).  Should we at least add `--without-filename`?
- In the `--man` output, two styles are used to describe boolean options: `--group`/`--nogroup` as well as `--[no]group`.  We should pick a style and be consistent.
- `--ignore-file`/`--ignore-dir` don't use ack2 filters in their documentation (specifically `--help`).

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#38
