### ISSUE TITLE
Feature idea: only select files that are tracked by the VCS

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#189]
This is a **far** future idea, probably something that would be done by plugins, but I still think it's worth documenting.

Sometimes, I'm working in a repository and I've got some build outputs.  Maybe I have some `dzil` generated files lying around; maybe I have a Makefile generated via Makefile.PL.  Either way, if I want to try and find something that would result in a change in the build outputs, I'd like to search for the original source (in the latter example, Makefile.PL).  I _could_ add the relevant lines to `.ackrc`, but it seems like this would be a pretty elegant solution.

**Comment by petdance** [comment]
I think this perennial favorite is going to have to go.
