### ISSUE TITLE
Do we need an option for forcing the printing of the line number?

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#196]
`-H` forces the printing of the filename (which implies printing of the line number), and grep has `-n` to print the line numbers only.  Do we need an equivalent to grep's `-n`?

**Comment by callumgare** [comment]
+1 currently I tack /dev/null on to the input files to force numbers but that's very inelegant.

**Comment by democtezuma** [comment]
You can just use `-H` on 1 or more files to show the line numbers (with filename).
It would be easier to add `-H` to your `.ackrc` file as well.

**Comment by xealits** [comment]
+1 I would like to have separate option for numbering the lines.
The filename in the workaround (`-H`, `--with-filenames` options) could be a nuisance when running some pipeline..

**Comment by ajlanghorn** [comment]
:+1: this.

**Comment by liavkoren** [comment]
:+1:

**Comment by petdance** [comment]
Closed and moved to feature requests.  I think we could add this to ack 3.
