### ISSUE TITLE
Allow distinguishing comments from code when searching.

### ISSUE THREAD

**Issue by powerman** [petdance/ack2#223]
It would be nice to search perl code independently from POD embedded in same file (and otherwise).

Real use case: look at something big like Mojolicious. It have a lot of documentation embedded in .pm files, and that documentation consists mostly of examples - which are perl code. So, when you run something like

```
    ack -- '->on\(request' Mojo*
```

you got 80% of results from POD and only 20% from module code.

Thing is, in most cases you look either for documentation OR for code, but not for both at one. While documentation doesn't contain code everything works fine, but if it contain a lot of real code examples... It makes no sense to ask grep to distinguish between perl code in code and in POD, but when we talk about ack it looks like native feature for it. :)

**Comment by petdance** [comment]
I would love this but I don't want to touch parsing of input files.
