### ISSUE TITLE
Apply subdirectory's .ackrc

### ISSUE THREAD

**Issue by mcandre** [petdance/ack2#273]
I would prefer that `.ackrc`'s in subdirectories are applied when searching them, no matter where your current directory is.

```
$ mkdir test
$ echo "shouldn't print" > test/test.dot
$ echo "--ignore-file=ext:dot" > test/.ackrc
$ ack print test/
test\test.dot
1:shouldn't print
$ cd test/
$ ack print
(blank)
```

**Comment by petdance** [comment]
This is more complex than I want to make .ackrcs.  Sorry.
