### ISSUE TITLE
Warn when invalid option comes from $PWD/.ackrc.

### ISSUE THREAD

**Issue by clonezone** [petdance/ack2#277]
Scenario: I got the code for a project that I’m not familiar with yet. I attempt to start looking around with ack, but it's not working, giving the "Option '-a' is not valid in ack 2" error. After spending a bunch of time seeing how ack could be screwed up, figured out that there was a .ackrc file in the codebase itself which was specifying the option.

Request: if there’s an invalid option and it didn’t come from the command-line, include the source of the option in the error.

**Comment by petdance** [comment]
Closed and moved to feature request wiki page.
