### ISSUE TITLE
Missing Getopt::Long::GetOptionsFromString in Perl 5.8.8

### ISSUE THREAD

**Issue by bart9h** [petdance/ack2#281]
When trying to run ack 2.04 on a RedHat 5 machine (Perl 5.8.8) I get:

Undefined subroutine &Getopt::Long::GetOptionsFromString called at line 4143.

**Comment by dolmen** [comment]
Making a CPAN release with the prereqs fixed would at least fix the issue for people installing from CPAN on perl 5.8

**Comment by petdance** [comment]
I hate to make a release that bumps up a Perl version unnecessarily, but I also see merit in that suggestion.

**Comment by dolmen** [comment]
`Getopt::Long` is not just bundled with perl: it is also available [on CPAN](https://metacpan.org/release/Getopt-Long). So perl 5.8 users who install `ack` from CPAN could stay with the same perl.

**Comment by petdance** [comment]
This is covered by #564 and #576

**Comment by dolmen** [comment]
Fixed by commit 9f6c3882c2088d261f00a7789134868c0b0e767f: Getopt::Long dependency upgraded to 2.38.
