### ISSUE TITLE
What does -f do?

### ISSUE THREAD

**Issue by CapnKernel** [petdance/ack2#292]
Hello,

I'm new to ack.  I was looking at the documentation and saw -f.  The docs for -f say: "Only print the files selected, without searching".  I can't tell from that what -f does., and I haven't been able to find anything more descriptive, nor have my experiments revealed what it does.

What does -f do?  (Maybe an example in the docs?)

I'm hoping, based on that text, that I can use it as a cross-platform way for my customers to locate the name of a file somewhere below the current directory, a la find -type f -name "$whatever".  But cross-platform.  Even if ack -f is not this, it would still be nice to know what -f does.

**Comment by petdance** [comment]
This has been done.
