### ISSUE TITLE
add --default_directory

### ISSUE THREAD

**Issue by wwalker** [petdance/ack2#310]
Currently, the default directory to search, if no file/directory is passed in, is cwd().

Our project is very wide and sometimes very deep.  I would need to pass in "../../../../../../../.." or ".." to search the whole project.

I envision default_directory=current|project|/full/path|relative_path

current = current working directory, currect ack behavior

full_path = user specifies a fully qualified path to the directory

relative_path = user specifies a path relative to where the .ackrc is ("." being "project top" if the .ackrc is in the project root or project source root)

project_top = the top of the current project based on the semantics of the VCS found (for git would be the first parent dir with .git, for SVN would be the last parent dir with .svn, similar for other VCS's)

A user like me who always wants project top, and all his projects use supported VCSs would put --default-directory=project_top in ~/.ackrc.

A user with an unsupported VCS (or no VCS, like an admin in /etc) would put a .ackrc file in the project top with --default-directory='.'

A user who wants to operate on part of the project dir (src or lib) would put a .ackrc file in the project top with --default-directory=src

**Comment by petdance** [comment]
Closed and moved to wiki page
