### ISSUE TITLE
New option idea: --tree

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#314]
This is probably too silly and unnecessary, but I think that having a `--tree` option would be kinda neat.  If you're not familiar with it, the `tree` command recursively lists files under the current directory in a pretty tree-like format.  For example:

![tree](https://f.cloud.github.com/assets/107804/1002768/15b20f30-0a82-11e3-813b-34ada3efca0f.png)

The `--tree` option would duplicate this logic for the `-f`, `-g`, and `-l` options.

**Comment by petdance** [comment]
Cool idea but I really don't wanna add it.
