### ISSUE TITLE
ACK_PAGER doesn't work when piping data through ack

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#354]
https://github.com/petdance/ack/issues/113

`--pager` works, but `ACK_PAGER` does not.

**Comment by h3xx** [comment]
I second @bartlomiejb's comment; it works as expected for me as well.

Using ack standalone v2.14.

**Comment by hoelzro** [comment]
Thanks for weighing in @bartlomiejb and @h3xx ; I'll close this then.
