### ISSUE TITLE
Help should not take user's settings into account.

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#358]
Help should not take user's settings into account. It should be
effectively --no-env.

I ran ack --help and got

Directories ignored by default:
autom4te.cache, blib, _build, .bzr, .cdv, cover_db, CVS, _darcs, ~.dep,
~.dot, .git, .hg, ~.nib, nytprof, .pc, ~.plst, RCS, SCCS, _sgbak and
.svn

That nytprof is in there because of my .ackrc settings, not part of ack itself.

**Comment by petdance** [comment]
`ack --help` no longer shows that directory list.
