### ISSUE TITLE
Improper highlighting for patterns with parenthesis

### ISSUE THREAD

**Issue by rkleemann** [petdance/ack2#364]
When specifying a pattern with a set of parenthesis, the highlighted portion is not the full match, but only the parenthesized portion.  Interestingly, -o outputs the correct thing.

For example:

```
$ ( echo foobar ; echo foobaz ; echo foobat ) | ack '\w+(bar|bat|baz)'
foo_bar_
foo_baz_
foo_bat_
```

Where the highlighted portions are surrounded by the underscores.

```
$ ack --version
ack 2.08
Running under Perl 5.14.4 at /Users/Shared/perl5/perls/perl-5.14.4/bin/perl
```

**Comment by petdance** [comment]
This is an intentional feature.  It is removed in ack3.

**Comment by rkleemann** [comment]
I disagree that this is an intentional feature, but I'll patiently wait for ack3 to address it.

**Comment by petdance** [comment]
I'm not sure how it is that you can "disagree" that it's a feature.

Go look at `print_line_with_options` and the section of code at `if ( @+ > 1 ) { # If we have captures...`

**Comment by rkleemann** [comment]
Ah, well then I have more faith in the description of it being an intended "feature".
