### ISSUE TITLE
Option '--type-set' not working correctly.

### ISSUE THREAD

**Issue by ericsubach** [petdance/ack2#389]
According to the [manual](http://beyondgrep.com/documentation/ack-2.10-man.html#defining_your_own_types), `--type-set` is the way to add a new type; `--type-add` is only for adding to an existing type. However, it seems that only `--type-add` will work.
#### .ackrc

```
--type-set=simple:ext:smpl
--nosimple
```
#### Steps
1. `echo 'this should work' > test.smpl`
2. `ack --simple work`. Expected output, but never got any.
3. Changing the `--type-set` to a `type-add` fixes the problem.
### Info

Ack version 2.10, tested on both linux mint 32-bit and Windows 64-bit strawberry perl (64-bit). Everything is default except the shown `.ackrc`.

**Comment by petdance** [comment]
This will go out in 2.17_02.  Thanks.
