### ISSUE TITLE
Missing extensions for some common types

### ISSUE THREAD

**Issue by Tux** [petdance/ack2#456]
My .ackrc contains (local (color) stuff stripped)

--8<---
--type-add=html:ext:xhtml
--type-add=xml:exe:xsd,wsdl

--ignore-directory=is:target
-->8---

.xhtml is an extension that I encounter quite often and does not show up under --dump. IMHO it should be added to html

.xsd and .wsdl are very clearly subject to the xml group and IMHO should be added to the default list of extensions for XML

the folder "target" should be skipped in netbeans/eclipse/maven project folders. Maybe only if the same folder exists with /src/ where the found folder has /target/

**Comment by petdance** [comment]
.xsd has been added elsewhere.

**Comment by petdance** [comment]
Done in eed2c4f.  This will go out in 2.17_01.  Thanks.
