### ISSUE TITLE
No way to ignore a file in a folder

### ISSUE THREAD

**Issue by AndrewRayCode** [petdance/ack2#479]
From http://stackoverflow.com/questions/24815522/how-do-i-make-ack-ignore-a-file-in-a-directory/24824663#24824663

I have a file in a directory `a/b/c.js`

I can't ignore `c.js` with `--ignore-file=match:c.js` because I want to match other file named `c.js`

I can't ignore dir `a/b` with `--ignore-dir=a/b` because **there are other files I care about in `a/b`**

I've tried:

```
--ignore-file=a/b/c.js       "Invalid filter specification"
```

I've tried:

```
--ignore-file=match:/a\/b\/c.js/
```

Doesn't work, and I'm guessing that it's because ack doesn't read the file path as part of the match, just the name.

I've tried:

```
--ignore-dir=match:/a\/b\/c.js/     " Non-is filters are not yet supported for --ignore-dir (what?)"
```

I can't find anything useful in the [Ack manual](http://beyondgrep.com/documentation/ack-2.12-man.html) soup. How do I ignore a file in a directory?

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#43

**Comment by petdance** [comment]
This will be addressed in ack3.
