### ISSUE TITLE
t/ack-s.t fails for non-English locale

### ISSUE THREAD

**Issue by eserte** [petdance/ack2#485]
Test failure with a German locale:

```
#   Failed test at t/ack-s.t line 47.
# [
#   'ack: foo: Keine Berechtigung'
# ]
# Looks like you failed 1 test of 4.
t/ack-s.t .................... 
```

Seen with ack 2.14 on FreeBSD and Linux systems.

**Comment by eserte** [comment]
Still fails with ack-2.15_01.

**Comment by hoelzro** [comment]
Relevant PR: https://github.com/petdance/file-next/pull/21

**Comment by eserte** [comment]
BTW, does not fail with perl 5.22.0, because stringified $! is now always English, regardless of user's locale (unless "use locale" is used within the perl code) (however, even if it's English it is possible that the "permission denied" message differs between operating systems).

**Comment by eserte** [comment]
Still fails with ack-2.15_02. Just saw a failure on a linux system with perl 5.20.3. More fail reports will probably follow...

**Comment by dolmen** [comment]
Still fails with ack-2.16 and File::Next 1.16.

**Comment by petdance** [comment]
This will go out in 2.17_01.
