### ISSUE TITLE
v2.14 with "-l" not emitting all matching files.

### ISSUE THREAD

**Issue by clonezone** [petdance/ack2#491]
Using standalone ack v2.14:

```
> echo ' ' >space-newline.txt
> echo $' \n' >space-newline-newline.txt
> ack ' $' space-newline*.txt
space-newline-newline.txt
1:

space-newline.txt
1: 
> ack -l ' $' space-newline*.txt
space-newline.txt
```

This works fine with standalone ack v2.12.

**Comment by karenetheridge** [comment]
@petdance can any assistance be rendered to do a release?

**Comment by karenetheridge** [comment]
I also just ran into a case where `ack ' $'` returned results, but `ack -l ' $'` returned nothing.

**Comment by shlomif** [comment]
@petdance : I can also help.

**Comment by hoelzro** [comment]
This should be fixed now.

**Comment by shlomif** [comment]
@hoelzro: thanks! Do you know when a new release will be made to CPAN?

**Comment by hoelzro** [comment]
@shlomif That's up to @petdance!

**Comment by shlomif** [comment]
@hoelzro : I see. It's been taking him a very long time, unfortunately.

**Comment by petdance** [comment]
Looks like this went out in 2.16.
