### ISSUE TITLE
Starting directory should override ignored directories

### ISSUE THREAD

**Issue by jamischarles** [petdance/ack2#524]
tl;dr Starting directory should override previously set ignore options (including defaults)

This issue is born out of #523 

Setup

```
mkdir temp
echo 'Bongo!' > temp/dir.txt
```

Tests
`ack --ignore-dir=temp Bongo temp` This should return a result but doesn't.
`ack -f --ignore-dir=temp temp` This should return dir.txt but doesn't.

**Comment by hoelzro** [comment]
@jamischarles This is resolved in Git HEAD as of 4091db4.

**Comment by jamischarles** [comment]
@hoelzro Awesome. When do you think this will make it into a release?

**Comment by hoelzro** [comment]
@jamischarles That's up to @petdance; I think he's been gearing up for a 2.16 release.

**Comment by petdance** [comment]
@jamischarles Can you please test this out on the dev branch, or the newly-released 2.15_02?

**Comment by usmonster** [comment]
Haven't tested, but what is the desired behavior for this use case:
```
mkdir temp foobar
echo 'Bongo!' > temp/dir.txt
cp temp/dir.txt foobar/
ack --ignore-dir=temp Bongo *
```
? Thanks!

**Comment by petdance** [comment]
Anything specified on the command line overrides whatever exclusions may happen because of switches.  In this case, `ack Bongo *` expands to `ack Bongo temp` and that `temp` overrides `--ignore-dir=temp`.

**Comment by usmonster** [comment]
Makes sense to me--thanks for the clarification!

**Comment by petdance** [comment]
This went out in 2.16.
