### ISSUE TITLE
Make the -a warning be clear that it is unnecessary.

### ISSUE THREAD

**Issue by petdance** [petdance/ack2#539]
https://gist.github.com/leto/eb928259ee9ba3662552 shows a frustrated Duke Leto not realizing that "ack1 -a foo" is equivalent to "ack2 foo".  The warning message for -a right now says:

```
Option '-a' is not valid in ack 2
This is because we now have -k/--known-types which makes it only select files
of known types, rather than any text file (which is the behavior of ack 1.x).
You may have options in a .ackrc, or in the ACKRC_OPTIONS environment variable.
Try using the --dump flag. 
```

What's missing is an explicit "You don't need -a, ack 1.x users."

**Comment by leto** [comment]
Yes, please! Obviously this is not intuitive for elderly Ack users who have stubborn muscle memories...

**Comment by petdance** [comment]
Obviously.

**Comment by petdance** [comment]
Updated the message in ac2fea1.  This will go out in 2.17_01.  Thanks.
