### ISSUE TITLE
Wrong man information on behavior in case of no named input files

### ISSUE THREAD

**Issue by gpoul** [petdance/ack2#543]
The information in the man page in file https://github.com/petdance/ack2/blob/dev/ack#L1136 seems to be wrong as it states that

`Ack searches the named input FILEs (or standard input if no files
are named, or the file name - is given) for lines containing a match
to the given PATTERN.`

but that doesn't seem to be the current behavior anymore, is it? Currently it seems that it does not read from standard input if no files are named.

**Comment by hoelzro** [comment]
@gpoul Thanks for pointing this out; it most definitely does not.

**Comment by petdance** [comment]
Updated.  Thanks.  7baceb4
