### ISSUE TITLE
Loud warning needed re MS Office files not searchable 

### ISSUE THREAD

**Issue by n1vux** [petdance/ack2#546]
surely we have FAQ not to search *.doc *.docx *.xlsx *.ppt etc, but apparently it could always be more obvious.  

(At least until Plugins enable DWIM here ! )

(documentation issue)

**Comment by petdance** [comment]
What should we say, and where?

**Comment by n1vux** [comment]
I don't recall the ack-users thread that spawned this issue, but noting that Office files are not the sort of text files supported by ack (or grep) in (more) prominent in the MAN/Help/webdoc as well as in FAQ would be a start. The philosophy of code search for coders doesn't seem to communicate to folks who want to search DOCX etc, possibly because to them DOCX is a text file (as it's not an Image and isn't Math).

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#32
