### ISSUE TITLE
Support to search in binary files

### ISSUE THREAD

**Issue by Sworddragon** [petdance/ack2#548]
I'm missing an option that does also search in all binary files and provide at least a hint like grep if there is a match. Maybe such an option could be added in ack 2.

**Comment by petdance** [comment]
Can you describe your use case for this, why you'd want to use ack for this task rather than grep that already does it just fine?

**Comment by Sworddragon** [comment]
As I know there is no way with grep to search a location without the help of external tools (like searching anything in /). This is the reason why I'm using ack in such cases as the usage is here more simple.

**Comment by petdance** [comment]
I don't think I understand what you're saying.  Are you saying that grep can't search / but ack can?  Tell me more.

**Comment by Sworddragon** [comment]
> Are you saying that grep can't search / but ack can?

Without external tools I don't know a way. If there should be any this ticket can be marked as invalid.

**Comment by petdance** [comment]
Show me how you're trying to search / with ack.  Are you just doing this?

    ack / somestring

And the equivalent grep doesn't work?

    grep -R somestring /

**Comment by Sworddragon** [comment]
Ah, grep is able to search a directory if a specific option is given. If you don't think ack needs then an option to search in binary files then just close this ticket.

**Comment by petdance** [comment]
Yes, with grep you must always specify a filename or directory to start at.  ack is different in that it assumes the current directory.
