### ISSUE TITLE
ack can get blocked by files

### ISSUE THREAD

**Issue by Sworddragon** [petdance/ack2#549]
Initially this issue was reported here: https://bugs.launchpad.net/ubuntu/+source/ack-grep/+bug/1267948
It is still reproducible with ack 2.14 and I'm assuming that it just hit a file that waits for input. Maybe ack should check for such files and then skip them.

**Comment by petdance** [comment]
What does grep do in such a situation?

**Comment by Sworddragon** [comment]
Grep does wait too.

**Comment by petdance** [comment]
If grep has the same problem, then I don't know that ack will be able to do any better.

**Comment by Sworddragon** [comment]
If I'm not wrong telling the file position should always fail on such files without blocking. This could be used as a way to detect such files.

**Comment by Sworddragon** [comment]
Just a little note: I have now also opened a ticket for this for grep on Launchpad: https://bugs.launchpad.net/ubuntu/+source/grep/+bug/1447216

**Comment by hoelzro** [comment]
Related: #214 #481

**Comment by xtaran** [comment]
I don't think this needs to be fixed at all because it is no bug but just how Linux works. Grepping through whole `/proc` just doesn't make sense as _all_ files in there are special and only have some file-ish properties.

**Comment by Sworddragon** [comment]
/proc was just an example but such files can appear at any location. For example applications could use /tmp to store such files there (for example the text editor SciTE is doing this).

**Comment by petdance** [comment]
Thanks for the input.  I'm closing this as acceptable.
