### ISSUE TITLE
Request for command line flag to control line buffering

### ISSUE THREAD

**Issue by unphased** [petdance/ack2#555]
Similar to BSD Grep's `--line-buffering` flag. 

For example I want to use `ack` to do a regex (which needs ack because regex has lookbehind) in a pipe with `fswatch`, the events trigger single lines of input over the pipe, so I'd like an immediate response, which buffers only lines.

**Comment by petdance** [comment]
I think you mean you want to disable line buffering, right?

**Comment by unphased** [comment]
Does it already do line buffering by default?

**Comment by petdance** [comment]
I'm confused when you say "I'd like an immediate response, which requires line buffering".  "immediate response" would require a given program to not have any line buffering.  An immediate response would mean that there is no buffer in the program for holding output.

**Comment by unphased** [comment]
Yes you are right, I edited a few things (but not the original content of the question). Does it clarify? I'm 100% satisfied now because turns out ack already by default does not do buffering. Which is what I wanted to begin with.

**Comment by petdance** [comment]
ack is written in Perl, and Perl by default *does* have output buffering on.  We do have the `--flush` option to turn that off:

  --flush                       Flush output immediately, even when ack is used
                                non-interactively (when output goes to a pipe or
                                file).

How did you conclude that ack does not do buffering by default?

**Comment by unphased** [comment]
I see. I concluded as I did because the behavior between `grep` and `ack` is different. When used with a pipe, `grep` continues buffering, but `ack` is smart and figures out to use `--flush` in that situation. 

Since you just showed me the flag, this answers the question. Thanks.
