### ISSUE TITLE
Support searching thru compressed files

### ISSUE THREAD

**Issue by nodakai** [petdance/ack2#566]
It would be great if we could do something like this:

```
$ ack '^E' 2015*.log.gz
20150111.log.gz
25:ERROR
60:ERROR
20150222.log.gz
80:ERROR
120:ERROR
```

**Comment by petdance** [comment]
This has been on the to-do list forever.  There's an issue for it already but I can't find it.

**Comment by hoelzro** [comment]
It's mentioned in #122.

**Comment by petdance** [comment]
What about tar archives?  Zip files?

**Comment by petdance** [comment]
Closed and added to https://github.com/petdance/ack2/wiki/Feature-requests
