### ISSUE TITLE
Enable colorizing of context line separator characters

### ISSUE THREAD

**Issue by h3xx** [petdance/ack2#568]
[(Discussion in ack-users)](https://groups.google.com/forum/#!topic/ack-users/z3zdKsqO7W4)

I tried to set the color of the context line separator characters in ack, but found ack lacks the options to do so. Ack only has support for uncolored separator characters.

The characters I'm talking about are the `:`, `-`, and `--` characters that decorate the output when you're searching with context lines turned on:

```
$ ack -H -C 1 z ~/.garbage
/home/me/.garbage
2-bar
3:baz
4-qux
--
25-bar
26:baz
27-qux
```

I've already implemented this feature in my own repo: https://github.com/h3xx/ack2/tree/feature-color-separator

Grep supports this already. Would anyone find this enhancement useful?

**Comment by petdance** [comment]
Closed and moved to Feature requests in wiki.
