### ISSUE TITLE
Revert b3617f1 and e3a5b3c

### ISSUE THREAD

**Issue by hoelzro** [petdance/ack2#572]
The optimizations introduced in the mentioned commits have caused various regressions (#571, #562, #491, #498), so in spite of the performance gains, they need to be reverted.  The revert isn't trivial (otherwise I would have done it), but it shouldn't take a determined contributor too long.

**Comment by hoelzro** [comment]
@petdance I've finished the revert and added some tests.  However, this invocation of ack still gives output:

    $ echo "\n\n\n" | ./tack '^(\s+)'  | wc -l
    4

This is because `\s` is matching the `\n` at the end of each line; to me, that's unrelated to this issue or the abovementioned ones.  Want me to file a new issue for this behavior and mark this issue as resolved?

**Comment by petdance** [comment]
The main task of reverting is done, right?  Can we make the still problematic note above be a new ticket?

**Comment by hoelzro** [comment]
@petdance Correct, and yes
