### ISSUE TITLE
Addition for Other Tools 'findwild'

### ISSUE THREAD

**Issue by n1vux** [petdance/ack2#578]
Mike Cornelison (Kornelix.com) is a solo producer of FLOSS for Debian/Ubuntu family of OS, probably best know for the Fotoxx photo editor. His miscellaneous utilities includes *findwild* http://www.kornelix.com/findwild.html 

- 
i am a fanatic about Fotoxx, i like his Watsup for CPU monitoring 2nd opinion, and have tinkered with some others. I'll be trying this, but being a Perl guy i'm sure i'll stick with 'ack'. From docs I see it solves many of the same problems as 'ack' but with different interface, plus modification date bracket (a 'find' feature we don't have). Will let you know what i think in comments ... and tickets if i think we need to steal an idea. Meantime, i'm sending him to look at ours so he can steal features.
"Plagiarism is basic to all culture." -- mis-attributed to PETE Seeger.

**Comment by petdance** [comment]
Migrated to https://github.com/petdance/beyondgrep/issues/42
