### ISSUE TITLE
Out of date FAQ: “Why isn't ack finding a match in (some file)?”

### ISSUE THREAD

**Issue by jwilk** [petdance/ack2#580]
The answer to the FAQ *Why isn't ack finding a match in (some file)?* reads:

> Probably because it's of a type that ack doesn't recognize.
> ack's searching behavior is driven by filetype. 
> If ack doesn't know what kind of file it is, ack ignores the file.

My understanding is that this is no longer true for ack 2.X.

**Comment by petdance** [comment]
Good catch.  Thank you.

**Comment by petdance** [comment]
Fixed in 2.51_02.
