### ISSUE TITLE
Addition of jspf files extension to jsp type

### ISSUE THREAD

**Issue by smonff** [petdance/ack2#586]
I noticed that the `jspf` extension is not included in the `jsp` type. I personally always add it manually to the `.ackrc`  file and it is ok this way, but it could be useful to have this *out of the box* for developers using JSP.

If you work with JSP files, there is a big chance that you also have to use JSPf(ragments), small pieces of reusable JSP that can be included inside them. 

What I suggest is:

````
type-add=jsp:ext:jsp,jspf,jspx,jhtm,jhtml
````
See also the [previous talk on the *ack-users* mailing list](https://groups.google.com/forum/#!topic/ack-users/qju6Zh3LGHw).

**Comment by petdance** [comment]
Added in 2.15_02.
