### ISSUE TITLE
Doc/man page should mention that -g option skips files not searched by ack (e.g. BINARY files)

### ISSUE THREAD

**Issue by theimpostor** [petdance/ack2#588]
The help text for the -g option should indicate that files that would not normally be searched by ack (i.e. BINARY files via the -T filetype check in the default filter), will not be included in the -g search.

I spent too much time trying to figure out why ack -g wasn't matching jar files, bz2 files that I knew where there...

**Comment by petdance** [comment]
Thanks for this.  Other thoughts: Emphasize that -g is a grep version of -f, and make sure people understand what -f is.

The overarching thing that people need to understand is that ack is not a general purpose file finding tool, and that it is not a replacement for grep or find.

**Comment by petdance** [comment]
Add a mention of -g to the FAQ question about -f.

**Comment by petdance** [comment]
Updated in bf74dcc.  Thanks.
