### ISSUE TITLE
Parameter -i does not work with capital Ø

### ISSUE THREAD

**Issue by geirmyk** [petdance/ack2#594]
I find this behaviour a bit strange:

This is ok:
$ echo 'abCØ' | ack -i c
abCØ

This fails:
$ echo 'abCØ' | ack -i ø

This is ok:
$ echo 'abCØ' | grep -i ø
abCØ

$ ack --version
ack 2.14
Running under Perl 5.18.2 at /usr/bin/perl

$ grep --version
grep (BSD grep) 2.5.1-FreeBSD

Running on OX X 10.11.3
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
My terminal supports UTF-8, by the way

**Comment by hoelzro** [comment]
@geirmyk Thanks for reporting!  Sorry, but ack doesn't really support Unicode; see #437 and #484, the latter of which has a workaround.
