### ISSUE TITLE
--pager="less -R" = command not found

### ISSUE THREAD

**Issue by jeffmacdonald** [petdance/ack2#600]
If you add --pager="less -R" to your .ackrc file and the run it  you get something like this:

(venv) mbp0 AWS-43 $ ack TODO
sh: less -R: command not found

**Comment by hoelzro** [comment]
Hi @jeffmacdonald, thanks for the report!  This is duplicate of #447; you can solve the issue by omitting the quotes around `less -R`.

**Comment by hoelzro** [comment]
I filed an issue #601 to document the options.

**Comment by jeffmacdonald** [comment]
Thanks for the info!
