### ISSUE TITLE
Fails with File::Next 1.14

### ISSUE THREAD

**Issue by andk** [petdance/ack2#602]
Both ack 2.15_02 and 2.14 generate fail reports when File::Next is at 1.14.

Downgrading to File::Next 1.12 brings the pass reports back.

Sample fail report: http://www.cpantesters.org/cpan/report/ff60af78-2ee3-11e6-8332-b246ee1f9a26

**Comment by hoelzro** [comment]
@petdance I've filed a PR against `File::Next` to resolve the issue.

**Comment by mikejw** [comment]
bump!

**Comment by petdance** [comment]
So it looks like we need File::Next 1.16 to get out, and then have ack have a dependency on 1.16?

**Comment by petdance** [comment]
Close this when #624 happens.

**Comment by petdance** [comment]
File::Next 1.16 is out.

**Comment by eserte** [comment]
Unfortunately ack-2.16 does not have a minimum version in the prereq requirement, so test failures still can happen.

**Comment by petdance** [comment]
Done. 89cadda
