### ISSUE TITLE
ack does not search stdin from terminal

### ISSUE THREAD

**Issue by fazjaxton** [petdance/ack2#603]
From the help text:

    ack may also search STDIN, but only if no file or directory arguments are
    specified, or if one of them is "-".

However, when no files are specified, ack recursively searches the current directory:

    ack .

And when "-" is specified, it is treated as a file name:

    $ ack . -
    ack: -: No such file or directory

I understand the usefulness of the first case, as this is probably what people mean 90+% of the time, but when the user explicitly asks for stdin (as in the second case), it would be nice to let them have it.

**Comment by petdance** [comment]
You're asking it to both descend through a tree AND search stdin.  I don't see how that would make sense to do.

**Comment by fazjaxton** [comment]
I don't want it to search through the tree.  In this case I mean "." as the pattern (matching anything).  The results are equivalent with "a":

    $ ack a

searches the tree, and:

    $ ack a -
    ack: -: No such file or directory

**Comment by petdance** [comment]
Ah, ok, you want `ack --filter`.

**Comment by petdance** [comment]
```
  --[no]filter                  Force ack to treat standard input as a pipe
                                (--filter) or tty (--nofilter)
```

**Comment by fazjaxton** [comment]
Oh, great!  Thanks!  Sorry, should have found that myself.  :)

**Comment by petdance** [comment]
Not a problem.  It took me a minute to find it myself. :-)
