### ISSUE TITLE
[documentation] Install command

### ISSUE THREAD

**Issue by strarsis** [petdance/ack2#608]
The command for installing ack in [ack documentation](http://beyondgrep.com/install/) assumes that the directory ~/bin already exists.
But this is not always the case, hence the command will fail.
The command could be changed a bit to ensure that this directory exists before proceeding:
````
mkdir -p ~/bin && curl http://beyondgrep.com/ack-2.14-single-file > ~/bin/ack && chmod 0755 !#:3
````

**Comment by petdance** [comment]
Are you referring to this page http://beyondgrep.com/install/ ?

**Comment by strarsis** [comment]
Yes, under section "Install the ack executable".

**Comment by petdance** [comment]
Oh duh, I didn't see the hyperlink you had.

I moved this over to the website's issue queue at https://github.com/petdance/beyondgrep/issues/52

Thanks for the report.
