### ISSUE TITLE
Document where the .ackrc is found

### ISSUE THREAD

**Issue by petdance** [petdance/ack2#611]
- /etc/ackrc
- ~/.ackrc
- .ackrc in the current directory or farther up the tree

Looking at the man page, I see that we don’t explicitly say that, and that’s a problem.

**Comment by senorsmile** [comment]
Ack is super helpful.  I'm looking to help where I can

It looks like this is already stated, under the ACKRC LOCATION SEMANTICS section; specifically starting on line 1991 (of the pod section): 

```
=item * Global ackrc

Options are then loaded from the global ackrc.  This is located at
C</etc/ackrc> on Unix-like systems.
```

```
=item * User ackrc

Options are then loaded from the user's ackrc.  This is located at
C<$HOME/.ackrc> on Unix-like systems.
```

```
=item * Project ackrc

Options are then loaded from the project ackrc.  The project ackrc is
```

Should this be referenced elsewhere too?

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#31
