### ISSUE TITLE
Provide an option in ack to only parse files passed to it.

### ISSUE THREAD

**Issue by toddr** [petdance/ack2#614]
In my environment, git grep is much faster at file finding than ack. Not to mention I only want to parse the files in the repo.

we have come up with a git alias that does what we want.

```
grack = "!f() { git grep -l -E $1 | ack -x --flush $* ;}; f"
```

The problem is that -x and --type are mutually exclusive (see https://github.com/petdance/ack2/issues/607)

My proposal is a -X option that does just tells ack which files it needs to parse explicitly, including deciding if the file type, etc is appropriate.

NOTE: looking at File::Next, it already provides from_file so if you do File::Next:: from_file('-'), This should be all we need to implement -X?

**Comment by petdance** [comment]
You would probably do it as a file_filter to the File::Next iterator.  But let's talk about behavior rather than implementation.

**Comment by hoelzro** [comment]
I'm confused - what would `-X` do differently from `-x`?

**Comment by petdance** [comment]
What I understand is that you want to be able to do:

    cat filelist.txt | ack -X --perl foo

which would only search for `foo` in files that were identified as Perl, and that came from filelist.txt.

More simply, you would have this:

    cat filelist.txt | ack -X --perl -f

which would then only list the files from filelist.txt that satisfy --perl.

Let's try to think of things that could go wrong with that.

**Comment by petdance** [comment]
Basically, `-X` would be `-x` that respected `--type`.

**Comment by toddr** [comment]
I didn't ask the question. Maybe I should. Other than legacy is there a good reason -x doesn't support --type?

**Comment by petdance** [comment]
`-x` doesn't support `--type` because `-x` says "This is the list of files you're going to use."  Think of how `xargs` reads arguments.  It says "I'm just going to get stuff from stdin".

**Comment by petdance** [comment]
Moved to https://github.com/petdance/ack2/wiki/Feature-requests
