### ISSUE TITLE
Highlighting wonky when using grouping

### ISSUE THREAD

**Issue by petek** [petdance/ack2#626]
Highlighting is not behaving as I would expect when I use grouping in certain cases.

To start, create a text file (`bar.txt`) with 3 lines:
```
     foo 
    _foo
    afoo
```

In the first case below, the highlighting is incorrect.  In all other cases, it is correct.
> $ ack '(^|[^\_])foo' bar.txt
> foo
> **a**foo
> $ ack '(^|[^\_])(foo)' bar.txt
> **foo**
> **afoo**
> $ ack '(?:^|[^\_])foo' bar.txt
> **foo**
> **afoo**
> $ ack '((^|[^\_])foo)' bar.txt
> **foo**
> **afoo**

**Comment by petdance** [comment]
This is an intentional feature.  It is removed in ack3.
