### ISSUE TITLE
ack hangs on an unfinished "|"

### ISSUE THREAD

**Issue by jalanb** [petdance/ack2#627]
Context: searching python code for `.split('|')`, so I used ack like
```
$ /usr/local/bin/ack --python 'split..|'
```

This resulted in ack showing me the name of the first matching file and then hanging. Quickly realised the silly mistake and retried with the `|` escaped
```
$ /usr/local/bin/ack --python 'split..\|'
```
which worked fine. So not really an issue for me, just thought you'd like to know.

For completeness, I tried the following, which found nothing (because I don't have any perl files in that dir), and came back without hanging.
```
$ /usr/local/bin/ack --perl 'split..|'
```
Adding a single `.pl` file, even an empty one, will then cause that command to hang

**Comment by hoelzro** [comment]
I'm guessing that the RHS of the `|` is matching the empty string, so the matching engine doesn't advance.  This looks to be happening with `.?` as well.

**Comment by hoelzro** [comment]
This appears to have been fixed in 80402b4cca94834795210fc6e25261f2d57eb049

**Comment by petdance** [comment]
This went out in 2.16.

**Comment by jalanb** [comment]
Works for me at verson 2.16
