### ISSUE TITLE
Emits a perl warning about uninitialized value when run from a removed directory

### ISSUE THREAD

**Issue by xtaran** [petdance/ack2#634]
Originally [reported in Debian](https://bugs.debian.org/781338) against ack 2.15_01, but I can also reproduce this with ack 2.14 as well as ack 2.15_03:

> This program emits a perl warning when it is run from a directory that has been removed. To demonstrate:
>
> ```
> $ mkdir /tmp/aaa
> $ cd /tmp/aaa
> $ rmdir /tmp/aaa
> $ ack foo
> Use of uninitialized value $cwd in pattern match (m//) at /usr/share/perl5/App/Ack/ConfigFinder.pm line 122.
> ```

**Comment by petdance** [comment]
Interesting.  Thanks for reporting.

**Comment by petdance** [comment]
Apparently this can return undef.

    my $cwd = Cwd::getcwd();

**Comment by petdance** [comment]
Fixed.  Will be released in 2.17_02.
