### ISSUE TITLE
SSL certificate for https://beyondgrep.com/ expired two days ago

### ISSUE THREAD

**Issue by a-rodin** [petdance/ack2#641]
Hi!

The SSL certificate for https://beyondgrep.com/ expired at May 19 2017, and plain HTTP doesn't work as well as it redirects to HTTPS version.

It also means that installer https://beyondgrep.com/ack-2.18-single-file cannot be downloaded with default security options of `curl` or `wget`.

Btw thank you for the amazing tool `Ack`! I use it extensively and don't look back to plain `grep` 👍:1st_place_medal:

**Comment by petdance** [comment]
Thanks for letting me know.  I renewed the certificate a couple of weeks ago so I was puzzled why this was a problem.  Turns out I didn't restart nginx after renewing the certificate. :-)

Thanks for the kind words about ack. Tell your friends!
