### ISSUE TITLE
ack "$" don't work

### ISSUE THREAD

**Issue by stephane-archer** [petdance/ack2#645]
if i type ack "$" nothing happen why??
ack 2.14
Running under Perl 5.22.1 at /usr/bin/perl

**Comment by petdance** [comment]
Hard to tell with limited information.  Tell me more.

What is in the directory you are in?  What exactly do you mean by "nothing happens"?

**Comment by stephane-archer** [comment]
I'm in my home directory, after typing the command the output i get is:
Name of a file\n
and it's wait for something indefinitely (It don't show me the match)

**Comment by petdance** [comment]
Can you please paste exact screenshots or text  cut & paste?

Also, how did you install ack?

**Comment by petdance** [comment]
And has it ever worked for you?  Is this the first time you're using ack?

**Comment by stephane-archer** [comment]
I use ack regulary (it's been one month i replace it from grep) I install it with apt on ubuntu :)

**Comment by stephane-archer** [comment]
if I type ack " $" it work perfectly or any other regexp, this this one don't work

**Comment by stephane-archer** [comment]
![ack](https://user-images.githubusercontent.com/2981437/28555182-f7b0aa64-70b2-11e7-8442-5b1fd1647a1e.png)

**Comment by petdance** [comment]
Are you wanting to find a literal dollar sign?  `$` is the metacharacter for the end of a line.  What if you do `ack "\$"` or `ack -Q "$"`?

Could your shell be doing some weird interpretation of that?  What if you have `ack '$'` to avoid any shell interpolation?  What if you do `echo "$"` vs. `echo '$'`?  What shell are you using?

Are you calling ack directly?  Are you wrapping it in a shell script at all?  What does `which ack` and `whereis ack` show?

I think either your shell is doing something goofy or there's something weird with `$` being the metacharacter for end of a line.

**Comment by stephane-archer** [comment]
ack '$' give the same result, I use zsh,
which ack give:
/usr/bin/ack
whereis ack give:
ack: /usr/bin/ack /usr/share/man/man1/ack.1p.gz

**Comment by petdance** [comment]
Somehow I think that your shell is messing with things.  What about the other things I asked?  What does `echo "$"` show?

Can you switch to bash and see what happens?

**Comment by stephane-archer** [comment]
ack "\$" don't work ack -Q "$" search the char $ but not the meta char :)

**Comment by stephane-archer** [comment]
echo "$" show:
$

**Comment by stephane-archer** [comment]
bash has the same behavior :)

**Comment by petdance** [comment]
This is a bug that's been fixed since 2.14.  You need a newer version.  It works fine in 2.16 and 2.18.

The big question is: Why are you acking for `$`, which is the end of the line?  Every line is going to match.

**Comment by stephane-archer** [comment]
I just wanted to report to you a bug to help.
I glad it's fix :)
Ubuntu is always terribly late....

**Comment by petdance** [comment]
But still I wonder: Why are you trying to match against `$`?

**Comment by stephane-archer** [comment]
I was matching with " $" to find some useless space on my files and I discover the bug but forgetting to put " " :)
